//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiskAssessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RiskAss_ResponseChoice
    {
        public int ID { get; set; }
        public int QuestionID { get; set; }
        public string Response { get; set; }
        public Nullable<int> RiskScore { get; set; }
    
        public virtual tbl_RiskAss_Questions tbl_RiskAss_Questions { get; set; }
    }
}
